# Generated by Django 4.1 on 2022-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_quantity", models.PositiveIntegerField()),
                ("product_name", models.CharField(max_length=200)),
                ("product_price", models.FloatField()),
            ],
        ),
    ]
